inherit_from:
    - .rubocop_airbnb.yml
 
#ここにはrubocopでコード解析したくないファイルやフォルダを指定します
AllCops:
    Exclude:
        - 'db/**/*'
        - 'bin/*'
        - 'config/environments/*'
        - 'config/application.rb'
        - 'config/initializers/*'
        - 'config/spring.rb'
        - 'config/deploy.rb'
        - 'lib/tasks/*'
        - 'vendor/**/*'
        - 'path/ruby'
        - 'spec/support/capybara.rb'

Metrics/LineLength:
    Max: 110
