version: 2.1
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          - PGHOST: 127.0.0.1
          - RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment: 
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_ROOT_HOST: 127.0.0.1
    working_directory: ~/chocobox
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum “Gemfile.lock” }}
          - v1-dependencies-
      - run: gem install bundler:2.0.2
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum “Gemfile.lock” }}
      - run: bundle exec rails db:create RAILS_ENV=test
      - run: bundle exec rails db:schema:load RAILS_ENV=test
      - run:
        name: RSpec
        command: bundle exec rspec

  workflows:
    version: 2.1
    rspec_and_rubocop:
      jobs:
        - rspec
      filters:
        branches:
          only: master
      