default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  #以下の3行が重要
  username: root
  password:
  host: db
  #
  timeout: 5000

development:
  <<: *default
  database: chocobox_development #sample_appの部分は、アプリ名に応じて修正

test:
  <<: *default
  database: chocobox_test #sample_appの部分は、アプリ名に応じて修正