default: &default
  adapter: sqlite3
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  #以下の3行が重要
  username: root
  password:
  host: db
  #
  timeout: 5000

development:
  <<: *default
  database: chocobox_development 

test:
  <<: *default
  database: chocobox_test 

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>